---
- name: Volume operations on PowerStore
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
  - name: Get volume details using ID
    register: vol_result
    dellemc.powerstore.dellemc_powerstore_volume:
      array_ip: "{{array_ip}}"
      verifycert: false
      user: "{{user}}"
      password: "{{password}}"
      vol_name: "{{vol_name}}"
      state: "present"

#   - name: return the response 
#     debug:
#       msg: "{{ vol_result['event_data']['res']['volume_details'] }}"
