#  Copyright (c) 2021 Dell Inc. or its subsidiaries.
#  All Rights Reserved.

- name: get volume information
  register: result_vol    
  dellemc.powerstore.dellemc_powerstore_volume:
    array_ip: "{{array_ip}}"
    verifycert: "{{verifycert}}"
    user: "{{user}}"
    password: "{{password}}"
    vol_name: "{{vol_name}}"
    state: "present"
